name: "CI"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  smoke:
    name: "Smoke test"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: "Install dependencies (Linux)"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/opt/vde
          make
          sudo make install
      - name: "Smoke test"
        run: |
          /opt/vde/bin/vde_switch --version
